### ISSUE TITLE
Java Exception

### ISSUE THREAD

**Issue by LeeThompson** [joakibj/tswrdb#6]
I'm sure this is probably a dead project but just in case, trying to run using java runtime:

```
java -jar tswrdb-0.0.1.jar export rdbtype 1020005 --tsw """C:\Games\The Secret World"""
```

```
Exception in thread "main" java.io.IOException: The filename, directory name, or
 volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.Win32FileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at com.joakibj.tswrdb.CommandDispatcher.dispatch(CommandDispatcher.scala:20)
        at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:93)
        at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:92)
        at scala.Option.map(Option.scala:145)
        at com.joakibj.tswrdb.TswRdb$delayedInit$body.apply(TswRdb.scala:91)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at com.joakibj.tswrdb.TswRdb$.main(TswRdb.scala:27)
        at com.joakibj.tswrdb.TswRdb.main(TswRdb.scala)[
```

```
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Win7 x64 SP1
```

**Comment by joakibj** [comment]
Ah right, the """ is a shell feature and I use the MSYS shell on windows

To run in cmd.exe, try:

```
java -jar tswrdb-0.0.1.jar export rdbtype 1020005 --tsw C:\Games\The Secret World
```

Without the quotation marks

**Comment by LeeThompson** [comment]
Not working for me.

`C:\Tools\java\bin\java -jar C:\Temp\tswrdb-0.0.1.jar export rdbtype 1020005 --tsw C:\Games\The Secret World`

I should note, I'm invoking the command line in the folder where I want the extracted files to go.

OS: Windows 7 Ultimate x64

CMD is elevated.

```
Error: Unknown argument 'Secret'
Error: Unknown argument 'World'
tswrdb 0.0.1
Usage: tswrdb [list|export|index] [options]

 (continues)
```

Update:
`C:\Tools\java\bin\java -jar C:\Temp\tswrdb-0.0.1.jar export rdbtype 1020005 --tsw "C:\Games\The Secret World"` worked

**Comment by joakibj** [comment]
Ah yeah, the spaces. Glad you found out, I don't really work much with the default windows shell
