### ISSUE TITLE
Invalid file path when attempting 1010001 (FME Mesh Data)

### ISSUE THREAD

**Issue by wodiesan** [joakibj/tswrdb#8]
So I'm ultimately trying to extract the in-game models. I ran:

``` java
run export rdbtype 1000010 --tsw """G:\The Secret World"""
```

Which worked fine.

``` java
[info] Running com.joakibj.tswrdb.TswRdb export rdbtype 1000010 --tsw G:\The Secret World
[info] TSW directory set to: G:\The Secret World
[info] Exporting RdbType: 1000010 (File Names) into exported/1000010 (File Names) ...
[info] Exporting entries from: 41.rdbdata
[success] Total time: 14 s, completed Jul 30, 2016 6:05:51 PM
```

When I ran this:

``` java
run export rdbtype 1010001 --tsw """G:\The Secret World"""
```

That's when things started crumbling:

``` java
[info] Running com.joakibj.tswrdb.TswRdb export rdbtype 1010001 --tsw G:\The Secret World
[info] TSW directory set to: G:\The Secret World
[info] Exporting RdbType: 1010001 (FME Mesh Data) into exported/1010001 (FME Mesh Data) ...
[info] Exporting entries from: 00.rdbdata
[error] java.lang.RuntimeException: Unknown unrecoverable exception occured: java.io.FileNotFoundException: Invalid file path
[info] Unknown unrecoverable exception occured: java.io.FileNotFoundException: Invalid file path
[info] Exiting...
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter$$anonfun$export$1.apply$mcVI$sp(RdbDataExporter.scala:56)
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter$$anonfun$export$1.apply(RdbDataExporter.scala:43)
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter$$anonfun$export$1.apply(RdbDataExporter.scala:43)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[error]         at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter.export(RdbDataExporter.scala:42)
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter.exportAll(RdbDataExporter.scala:28)
[error]         at com.joakibj.tswrdb.commands.ExportCommands$RdbTypeExportCommand.execute(ExportCommands.scala:30)
[error]         at com.joakibj.tswrdb.CommandDispatcher.execute(CommandDispatcher.scala:45)
[error]         at com.joakibj.tswrdb.CommandDispatcher.dispatch(CommandDispatcher.scala:31)
[error]         at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:93)
[error]         at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:92)
[error]         at scala.Option.map(Option.scala:145)
[error]         at com.joakibj.tswrdb.TswRdb$delayedInit$body.apply(TswRdb.scala:91)
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:71)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:71)
[error]         at scala.collection.immutable.List.foreach(List.scala:318)
[error]         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
[error]         at scala.App$class.main(App.scala:71)
[error]         at com.joakibj.tswrdb.TswRdb$.main(TswRdb.scala:27)
[error]         at com.joakibj.tswrdb.TswRdb.main(TswRdb.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]         at java.lang.reflect.Method.invoke(Unknown Source)
[error]         at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
[error]         at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
[error]         at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
[error]         at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
[error]         at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
[error]         at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
[error]         at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
[error]         at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
[error]         at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last tswrdb-cmdui/compile:run for the full output.
[error] (tswrdb-cmdui/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 16 s, completed Jul 30, 2016 6:17:25 PM
```

It did create an empty `1010001 (FME Mesh Data)` folder. I also tried flipping the slash to `run export rdbtype 1010001 --tsw """G:/The Secret World"""`, but it results in the same error.

Any help would be awesome. Thanks!

**Comment by joakibj** [comment]
Is that the only RDB type that does not work? If so, that ID might be outdated and thus no longer exists in newer versions of TSW. The list of IDs were compiled based on assumptions 3+ years ago.

**Comment by wodiesan** [comment]
I tried a few of them, including `1010004 (Textures)`, which also failed. So far I only got the initial one working. Bevisbear recently posted some instructions [on his site](https://tswrdb.net/archives/519) which mentions the 10100001 ID, but let me try out some of the other RDB types.

**Comment by wodiesan** [comment]
I ended up using bevisbear's tool to extract the FME meshes. He was kind enough to make a [video guide on how to use both his and your tool](https://youtu.be/vzChsmS9hU4). The problem that I ran into with his tool is [explained here](https://youtu.be/ESUpO9Wx53I). Thanks again for the tool and the quick response!

**Comment by joakibj** [comment]
No worries, glad you found a solution :+1: . Hopefully the tool has been useful in other ways too.

**Comment by wodiesan** [comment]
[You contributed to this.](https://twitter.com/TheSecretWorld/status/760842096190296064) Thanks again!
Oh, and just so you're aware, someone was able to [use your tool with Java 8](https://forums.thesecretworld.com/showthread.php?97250-IRL-Gaia-Engine&p=2016496&viewfull=1#post2016496).
